apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "stdiscosrv.fullname" . }}
  labels:
    app: {{ template "stdiscosrv.name" . }}
    chart: {{ template "stdiscosrv.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "stdiscosrv.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "stdiscosrv.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
{{- if .Values.stdiscosrv.debug.enabled }}
            - -debug
{{- end }}
{{- if .Values.stdiscosrv.discovery.http.enabled }}
            - -http
{{- end }}
            - -listen={{ .Values.stdiscosrv.discovery.listen.address }}:{{ .Values.stdiscosrv.discovery.listen.port }}
{{- if .Values.stdiscosrv.metrics.enabled }}
            - -metrics-listen={{ .Values.stdiscosrv.metrics.listen.address }}:{{ .Values.stdiscosrv.metrics.listen.port }}
{{- end }}
{{- if .Values.stdiscosrv.replication.enabled }}
{{- if .Values.stdiscosrv.replication.peers }}
            - -replicate-peers={{ .Values.stdiscosrv.replication.peers }}
{{- end }}
            - -replication-listen={{ .Values.stdiscosrv.replication.listen.address }}:{{ .Values.stdiscosrv.replication.listen.port }}
{{- end }}
{{- if .Values.extraArgs }}
{{ toYaml .Values.extraArgs | indent 12 }}
{{- end }}
          env:
{{- if .Values.extraArgs }}
{{ toYaml .Values.extraEnv | indent 12 }}
{{- end }}
          ports:
            - name: discovery
              containerPort: {{ .Values.stdiscosrv.discovery.listen.port }}
              protocol: TCP
            {{- if .Values.stdiscosrv.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.stdiscosrv.metrics.listen.port }}
              protocol: TCP
            {{- end }}
            {{- if .Values.stdiscosrv.replication.enabled }}
            - name: replication
              containerPort: {{ .Values.stdiscosrv.replication.listen.port }}
              protocol: TCP
            {{- end }}
          # TODO
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: data
            mountPath: /stdiscosrv
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "stdiscosrv.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
    {{- end }}
