apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "stdiscosrv.fullname" . }}
  labels:
    app: {{ template "stdiscosrv.name" . }}
    chart: {{ template "stdiscosrv.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "stdiscosrv.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "stdiscosrv.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.stdiscosrv.cert }}
            - -cert={{ .Values.stdiscosrv.cert }}
            {{- end }}
            {{- if .Values.stdiscosrv.dbDir }}
            - -db-dir={{ .Values.stdiscosrv.dbDir }}
            {{- end }}
            {{- if .Values.stdiscosrv.debug }}
            - -debug
            {{- end }}
            {{- if .Values.stdiscosrv.http }}
            - -http
            {{- end }}
            {{- if .Values.stdiscosrv.key }}
            - -key={{ .Values.stdiscosrv.key }}
            {{- end }}
            - -listen={{ .Values.stdiscosrv.listen.address }}:{{ .Values.stdiscosrv.listen.port }}
            {{- if .Values.stdiscosrv.metrics.enabled }}
            - -metrics-listen={{ .Values.stdiscosrv.metrics.listen.address }}:{{ .Values.stdiscosrv.metrics.listen.port }}
            {{- end }}
            {{- if .Values.stdiscosrv.replicate }}
            - -replicate={{ .Values.stdiscosrv.replicate }}
            {{- end }}
            - -replication-listen={{ .Values.stdiscosrv.replication.listen.address }}:{{ .Values.stdiscosrv.replication.listen.port }}
            {{- if .Values.extraArgs }}
{{ toYaml .Values.extraArgs | indent 12 }}
            {{- end }}
          {{- if .Values.extraEnv }}
          env:
{{ toYaml .Values.extraEnv | indent 12 }}
          {{- end }}
          ports:
            - name: discovery
              containerPort: {{ .Values.stdiscosrv.listen.port }}
              protocol: TCP
            {{- if .Values.stdiscosrv.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.stdiscosrv.metrics.listen.port }}
              protocol: TCP
            {{- end }}
            - name: replication
              containerPort: {{ .Values.stdiscosrv.replication.listen.port }}
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: data
            mountPath: /stdiscosrv
          {{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
          {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "stdiscosrv.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 6 }}
      {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
    {{- end }}
